[package]
name = "reth-pulsechain-consensus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "PulseChain consensus implementation"

[lints]
workspace = true

[dependencies]
# Reth
reth-chainspec.workspace = true
reth-consensus.workspace = true
reth-consensus-common.workspace = true
reth-ethereum-consensus.workspace = true
reth-ethereum-primitives.workspace = true
reth-node-api.workspace = true
reth-node-builder.workspace = true
reth-primitives-traits.workspace = true

# Alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true

# Misc
eyre.workspace = true
reth-execution-types.workspace = true
tracing.workspace = true

# PulseChain
reth-pulsechain-forks = { path = "../hardforks" }

[dev-dependencies]
reth-pulsechain-chainspec = { path = "../chainspec" }

[features]
default = ["std"]
std = []
