[package]
name = "reth-pulsechain-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "PulseChain EVM and executor for pulse-reth"

[lints]
workspace = true

[dependencies]
# reth
reth-ethereum = { workspace = true, features = ["evm", "node-api", "node", "provider", "rpc"] }
reth-pulsechain.workspace = true
reth-pulsechain-forks.workspace = true

# ethereum
alloy-primitives.workspace = true
alloy-evm.workspace = true
alloy-consensus.workspace = true

# revm
revm.workspace = true

# misc
tracing.workspace = true
eyre.workspace = true

[dev-dependencies]
reth-pulsechain-chainspec.workspace = true

[features]
default = ["std"]
std = [
    "alloy-primitives/std",
    "reth-pulsechain/std",
]
