[package]
name = "reth-pulsechain-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "PulseChain node implementation for pulse-reth"

[lints]
workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
reth-engine-local.workspace = true
reth-ethereum.workspace = true
reth-ethereum-engine-primitives.workspace = true
reth-ethereum-primitives.workspace = true
reth-node-api.workspace = true
reth-node-builder.workspace = true
reth-payload-primitives.workspace = true
reth-provider.workspace = true

# pulsechain
reth-pulsechain-evm.workspace = true

# alloy
alloy-rpc-types-eth.workspace = true

[features]
default = ["std"]
std = []

[dev-dependencies]
reth-node-builder = { workspace = true, features = ["test-utils"] }
